-- MySQL Script generated by MySQL Workbench
-- Mon Mar 15 15:00:40 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema webstart_automobile
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema webstart_automobile
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `webstart_automobile` DEFAULT CHARACTER SET utf8 ;
USE `webstart_automobile` ;

-- -----------------------------------------------------
-- Table `webstart_automobile`.`Véhicule`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `webstart_automobile`.`Véhicule` (
  `idVéhicule` INT NOT NULL AUTO_INCREMENT,
  `Titre` VARCHAR(255) NOT NULL,
  `Modèle` VARCHAR(45) NOT NULL,
  `decription` MEDIUMTEXT NULL,
  `created_at` DATETIME NULL,
  `uptated_at` DATETIME NULL,
  `marque_idmarque` INT NOT NULL,
  `Photo_idPhoto` INT NOT NULL,
  PRIMARY KEY (`idVéhicule`),
  INDEX `fk_Véhicule_marque1_idx` (`marque_idmarque` ASC) VISIBLE,
  INDEX `fk_Véhicule_Photo1_idx` (`Photo_idPhoto` ASC) VISIBLE,
  CONSTRAINT `fk_Véhicule_marque1`
    FOREIGN KEY (`marque_idmarque`)
    REFERENCES `webstart_automobile`.`marque` (`idmarque`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Véhicule_Photo1`
    FOREIGN KEY (`Photo_idPhoto`)
    REFERENCES `webstart_automobile`.`Photo` (`idPhoto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `webstart_automobile`.`Marques`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `webstart_automobile`.`Marques` (
  `id` INT NOT NULL,
  `Titre` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `webstart_automobile`.`photo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `webstart_automobile`.`photo` (
  `idPhotos` INT NOT NULL AUTO_INCREMENT,
  `created at` DATE NULL,
  `uptated at` DATE NULL,
  `Véhicule_idVéhicule` INT NOT NULL,
  PRIMARY KEY (`idPhotos`),
  INDEX `fk_photo_Véhicule1_idx` (`Véhicule_idVéhicule` ASC) VISIBLE,
  CONSTRAINT `fk_photo_Véhicule1`
    FOREIGN KEY (`Véhicule_idVéhicule`)
    REFERENCES `webstart_automobile`.`Véhicule` (`idVéhicule`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `webstart_automobile`.`Home`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `webstart_automobile`.`Home` (
  `idHome` INT NOT NULL AUTO_INCREMENT,
  `Title` VARCHAR(45) NULL,
  `introduction` MEDIUMTEXT NULL,
  `created at` VARCHAR(45) NULL,
  `uptated at` VARCHAR(45) NULL,
  `Véhicule_idVéhicule` INT NOT NULL,
  PRIMARY KEY (`idHome`),
  INDEX `fk_Home_Véhicule1_idx` (`Véhicule_idVéhicule` ASC) VISIBLE,
  CONSTRAINT `fk_Home_Véhicule1`
    FOREIGN KEY (`Véhicule_idVéhicule`)
    REFERENCES `webstart_automobile`.`Véhicule` (`idVéhicule`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `webstart_automobile`.`marque`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `webstart_automobile`.`marque` (
  `idmarque` INT NOT NULL AUTO_INCREMENT,
  `Titre` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`idmarque`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `webstart_automobile`.`Photo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `webstart_automobile`.`Photo` (
  `idPhoto` INT NOT NULL AUTO_INCREMENT,
  `Titre` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`idPhoto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `webstart_automobile`.`Véhicule`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `webstart_automobile`.`Véhicule` (
  `idVéhicule` INT NOT NULL AUTO_INCREMENT,
  `Titre` VARCHAR(255) NOT NULL,
  `Modèle` VARCHAR(45) NOT NULL,
  `decription` MEDIUMTEXT NULL,
  `created_at` DATETIME NULL,
  `uptated_at` DATETIME NULL,
  `marque_idmarque` INT NOT NULL,
  `Photo_idPhoto` INT NOT NULL,
  PRIMARY KEY (`idVéhicule`),
  INDEX `fk_Véhicule_marque1_idx` (`marque_idmarque` ASC) VISIBLE,
  INDEX `fk_Véhicule_Photo1_idx` (`Photo_idPhoto` ASC) VISIBLE,
  CONSTRAINT `fk_Véhicule_marque1`
    FOREIGN KEY (`marque_idmarque`)
    REFERENCES `webstart_automobile`.`marque` (`idmarque`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Véhicule_Photo1`
    FOREIGN KEY (`Photo_idPhoto`)
    REFERENCES `webstart_automobile`.`Photo` (`idPhoto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `webstart_automobile`.`Brand`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `webstart_automobile`.`Brand` (
  `idBrand` INT NOT NULL,
  `Title` VARCHAR(255) NULL,
  PRIMARY KEY (`idBrand`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `webstart_automobile`.`Cars`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `webstart_automobile`.`Cars` (
  `idcars` INT NOT NULL,
  `Titre` VARCHAR(255) NOT NULL,
  `Modèle` VARCHAR(255) NULL,
  `Description` DATETIME NULL,
  `created_at` DATETIME NULL,
  `Brand_idBrand` INT NOT NULL,
  PRIMARY KEY (`idcars`),
  INDEX `fk_Cars_Brand1_idx` (`Brand_idBrand` ASC) VISIBLE,
  CONSTRAINT `fk_Cars_Brand1`
    FOREIGN KEY (`Brand_idBrand`)
    REFERENCES `webstart_automobile`.`Brand` (`idBrand`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `webstart_automobile`.`Pictures`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `webstart_automobile`.`Pictures` (
  `idPictures` INT NOT NULL,
  `Title` VARCHAR(255) NULL,
  `Picturescol` VARCHAR(45) NULL,
  `Cars_idcars` INT NOT NULL,
  PRIMARY KEY (`idPictures`),
  INDEX `fk_Pictures_Cars1_idx` (`Cars_idcars` ASC) VISIBLE,
  CONSTRAINT `fk_Pictures_Cars1`
    FOREIGN KEY (`Cars_idcars`)
    REFERENCES `webstart_automobile`.`Cars` (`idcars`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `webstart_automobile`.`Marques`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `webstart_automobile`.`Marques` (
  `id` INT NOT NULL,
  `Titre` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `webstart_automobile`.`Véhicules`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `webstart_automobile`.`Véhicules` (
  `id` INT NOT NULL,
  `Titre` VARCHAR(255) NOT NULL,
  `Modéle` VARCHAR(255) NOT NULL,
  `description` MEDIUMTEXT NULL,
  `prix` VARCHAR(45) NOT NULL,
  `couleur` VARCHAR(45) NOT NULL,
  `created_at` DATETIME NULL,
  `uptated_at` DATETIME NULL,
  `Marques_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Véhicules_Marques1_idx` (`Marques_id` ASC) VISIBLE,
  CONSTRAINT `fk_Véhicules_Marques1`
    FOREIGN KEY (`Marques_id`)
    REFERENCES `webstart_automobile`.`Marques` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `webstart_automobile`.`Images`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `webstart_automobile`.`Images` (
  `id` INT NOT NULL,
  `Titre` VARCHAR(255) NULL,
  `Véhicules_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Images_Véhicules1_idx` (`Véhicules_id` ASC) VISIBLE,
  CONSTRAINT `fk_Images_Véhicules1`
    FOREIGN KEY (`Véhicules_id`)
    REFERENCES `webstart_automobile`.`Véhicules` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
